apiVersion: v1
kind: Secret
metadata:
  name: haruki-event-tracker-config
type: Opaque
stringData:
  haruki-tracker-configs.yaml: |
    backend:
      host: 0.0.0.0
      port: 8080
      ssl: false
      log_level: INFO
      main_log_file: ""
      access_log_path: ""
      enable_trust_proxy: true
      trusted_proxies:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
      proxy_header: "X-Forwarded-For"

    servers:
      jp:
        enabled: true
        master_data_dir: "s3://example-bucket/haruki/master/jp?region=ap-northeast-1"
        tracker:
          enabled: false
          use_second_level_cron: false
          cron: "*/2 * * * *"
        gorm_config:
          dialect: postgres
          dsn: "postgres://haruki:CHANGE_ME@postgres.default.svc.cluster.local:5432/haruki_tracker_jp?sslmode=disable"
          max_open_conns: 20
          max_idle_conns: 2
          conn_max_lifetime: 1h

