apiVersion: v1
kind: Service
metadata:
  name: haruki-event-tracker
  labels:
    app.kubernetes.io/name: haruki-event-tracker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: haruki-event-tracker
  ports:
    - name: http
      port: 8080
      targetPort: http
