bind = ["127.0.0.1:9232"]
loglevel = "info"
access_log_format = "%(h)s %(r)s %(s)s %(b)s %(M)s"
keep_alive_timeout = 10
workers = 1
# worker_class = "uvloop" # High asyncio event loop performance suggestion.